In [6]:
import pandas as pd

df1= pd.read_csv('twse_monthly_revenue_mock_200.csv')

df1

,出表日期,資料年月,公司代號,公司名稱,產業別,營業收入-當月營收,營業收入-上月營收,營業收入-去年當月營收,營業收入-上月比較增減(%),營業收入-去年同月增減(%),累計營業收入-當月累計營收,累計營業收入-去年累計營收,累計營業收入-前期比較增減(%),備註
0,1110912,11108,1100,測試公司1,光電業,304759,318466,267547,-4.304070,13.908584,2133313,2205213,-3.260456,季節性因素
1,1110912,11108,1101,測試公司2,半導體業,3759644,3663471,3596154,2.625188,4.546246,30077152,25988772,15.731332,營收成長
2,1110912,11108,1102,測試公司3,半導體業,5033473,4088464,3916409,23.114035,28.522659,25167365,22372630,12.491759,-
3,1110912,11108,1103,測試公司4,半導體業,7462356,6628245,6826115,12.584191,9.320690,59698848,52176597,14.416906,營收成長
4,1110912,11108,1104,測試公司5,半導體業,1025358,866498,1160113,18.333568,-11.615679,5126790,4569084,12.206079,營收成長
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1110912,11108,1295,測試公司196,光電業,8611680,9894583,6390097,-12.965711,34.766029,68893440,60667049,13.559900,營收下滑
196,1110912,11108,1296,測試公司197,其他電子業,5908689,5678954,6795816,4.045375,-13.054017,29543445,31286070,-5.569971,營收下滑
197,1110912,11108,1297,測試公司198,半導體業,6181398,6455822,7785126,-4.250799,-20.599898,49451184,54638104,-9.493228,營收下滑
198,1110912,11108,1298,測試公司199,水泥工業,2198044,1958192,1840165,12.248646,19.448202,17584352,16257440,8.161875,需求增加
199,1110912,11108,1299,測試公司200,其他電子業,622357,591797,710570,5.163933,-12.414400,3111785,3064650,1.538022,-

In [12]:
df1.iloc[0:5, 0:3]

      出表日期   資料年月  公司代號
0  1110912  11108  1100
1  1110912  11108  1101
2  1110912  11108  1102
3  1110912  11108  1103
4  1110912  11108  1104