In [2]:
import numpy as np
import pandas as pd

students = np.random.randint(50, high=101, size=(50, 5))
students_df = pd.DataFrame(students, index=[f"Student#{i}" for i in range(1,51)], columns=['Math', 'Science', 'English', 'History', 'Art'])
students_df

            Math  Science  English  History  Art
Student#1     74       92       73       64   63
Student#2     51       63      100       99   87
Student#3     86       62       54       88   71
Student#4     91       81       58       65   99
Student#5     70       85       59       96   87
Student#6     70       83       76       57   67
Student#7     52       52       52       95   58
Student#8     74       62       81       59   99
Student#9     62       77       69       67   70
Student#10    98       98       74       77   87
Student#11    58       77       64       91   81
Student#12    81       60       94       64   52
Student#13    98       64       65       94   58
Student#14    50       62       61       79   55
Student#15    97       61       70       53   77
Student#16    71       98       69       52   62
Student#17    83       99       58       88   65
Student#18    74       51       73       80   90
Student#19    73       76      100       99   94
Student#20    63       78       89       66  100
Student#21    61       70       73       61   56
Student#22    88      100       93       85   68
Student#23    88       50       88       84   72
Student#24    50       55       98       99   83
Student#25    97       75       69       78   81
Student#26    78       84       58       61   74
Student#27    50       86       69       84   97
Student#28    68       56       50       66   96
Student#29    52       93       80       70   87
Student#30    63       76      100       95   87
Student#31    99       70       62       55   90
Student#32    62       60       51       99   59
Student#33    98       96       76       70   83
Student#34    81       99       55       77   90
Student#35    74       90       89       80   54
Student#36    66       61       86       53   63
Student#37    61       98       68       62   94
Student#38    72       62       74       86   88
Student#39    60       68       94       74   79
Student#40    74       96       89       84   93
Student#41    92       86       84       84   54
Student#42    68       54       50       60   91
Student#43    73       69       58       89   79
Student#44    59       52       71       67   65
Student#45    58       70       98       69   82
Student#46    97       70       91       66   98
Student#47    86       92       55       83   50
Student#48    54       57       78       50   90
Student#49    71       64       97       91   68
Student#50    72       90       94       69   87

In [ ]:
students_df.iloc[0]  #透過index位置選取第一位學生

Math       74
Science    92
English    73
History    64
Art        63
Name: Student#1, dtype: int64

In [11]:
students_df.loc['Student#1'] #透過index名稱選取第一位學生

Math       74
Science    92
English    73
History    64
Art        63
Name: Student#1, dtype: int64

In [16]:
students_df.loc[['Student#1','Student#2']]

           Math  Science  English  History  Art
Student#1    74       92       73       64   63
Student#2    51       63      100       99   87

In [14]:
students_df.loc[('Student#1','Student#2'), ['Math','Science']]

           Math  Science
Student#1    74       92
Student#2    51       63

In [17]:
students_df.iloc[:5, :2]

           Math  Science
Student#1    74       92
Student#2    51       63
Student#3    86       62
Student#4    91       81
Student#5    70       85