In [2]:
from tools import all_years_merge

all_data = all_years_merge()
all_data

#修改欄位名稱, trnOpDates:乘車日期, gateInComingCnt:進站人數, garteOutGoingCnt:出站人數

,trnOpDate,車站代碼,gateInComingCnt,gateOutGoingCnt,車站名稱,車站地址
0,20190102,920,2346,2731,八堵,基隆市暖暖區八堵路142號
1,20190102,7302,1492,1437,NaN,NaN
2,20190102,7378,1516,1750,NaN,NaN
3,20190102,7384,1494,1618,NaN,NaN
4,20190103,7344,1467,1477,NaN,NaN
...,...,...,...,...,...,...
8995,20241230,7362,1990,1864,八斗子,新北市瑞芳區建基路2段121號
8996,20241231,909,3120,3438,NaN,NaN
8997,20241231,7323,1903,1703,NaN,NaN
8998,20241231,7356,1882,1671,NaN,NaN
8999,20241231,7360,1942,1953,瑞芳,新北市瑞芳區鐵道里明燈路三段82號

In [8]:
from tools import all_years_merge
import pandas as pd

all_data = all_years_merge()
all_data

#修改欄位名稱, trnOpDates:乘車日期, gateInComingCnt:進站人數, garteOutGoingCnt:出站人數


# 修改欄位名稱
all_data = all_data.rename(columns={
    'trnOpDate': '乘車日期',
    'gateInComingCnt': '進站人數',
    'gateOutGoingCnt': '出站人數'
})

all_data

# 乘車日期改成時間格式
all_data['乘車日期'] = pd.to_datetime(
    all_data['乘車日期'].astype(str),
    format='%Y%m%d'
)

all_data

all_data['年份'] = all_data['乘車日期'].dt.year
all_data['月份'] = all_data['乘車日期'].dt.month

all_data.head()

        乘車日期  車站代碼  進站人數  出站人數 車站名稱           車站地址    年份  月份
0 2019-01-02   920  2346  2731   八堵  基隆市暖暖區八堵路142號  2019   1
1 2019-01-02  7302  1492  1437  NaN            NaN  2019   1
2 2019-01-02  7378  1516  1750  NaN            NaN  2019   1
3 2019-01-02  7384  1494  1618  NaN            NaN  2019   1
4 2019-01-03  7344  1467  1477  NaN            NaN  2019   1