In [2]:
from tools import all_years_merge

all_data = all_years_merge()
all_data

#修改欄位名稱, trnOpDates:乘車日期, gateInComingCnt:進站人數, garteOutGoingCnt:出站人數

,trnOpDate,車站代碼,gateInComingCnt,gateOutGoingCnt,車站名稱,車站地址
0,20190102,920,2346,2731,八堵,基隆市暖暖區八堵路142號
1,20190102,7302,1492,1437,NaN,NaN
2,20190102,7378,1516,1750,NaN,NaN
3,20190102,7384,1494,1618,NaN,NaN
4,20190103,7344,1467,1477,NaN,NaN
...,...,...,...,...,...,...
8995,20241230,7362,1990,1864,八斗子,新北市瑞芳區建基路2段121號
8996,20241231,909,3120,3438,NaN,NaN
8997,20241231,7323,1903,1703,NaN,NaN
8998,20241231,7356,1882,1671,NaN,NaN
8999,20241231,7360,1942,1953,瑞芳,新北市瑞芳區鐵道里明燈路三段82號

In [6]:
from tools import all_years_merge
import pandas as pd

all_data = all_years_merge()
all_data

#修改欄位名稱, trnOpDates:乘車日期, gateInComingCnt:進站人數, garteOutGoingCnt:出站人數


# 修改欄位名稱
all_data = all_data.rename(columns={
    'trnOpDate': '乘車日期',
    'gateInComingCnt': '進站人數',
    'gateOutGoingCnt': '出站人數'
})

all_data

# 乘車日期改成時間格式
all_data['乘車日期'] = pd.to_datetime(
    all_data['乘車日期'].astype(str),
    format='%Y%m%d'
)

all_data

all_data['年份'] = all_data['乘車日期'].dt.year
all_data['月份'] = all_data['乘車日期'].dt.month

all_data.head()

        乘車日期  車站代碼  進站人數  出站人數 車站名稱           車站地址    年份  月份
0 2019-01-02   920  2346  2731   八堵  基隆市暖暖區八堵路142號  2019   1
1 2019-01-02  7302  1492  1437  NaN            NaN  2019   1
2 2019-01-02  7378  1516  1750  NaN            NaN  2019   1
3 2019-01-02  7384  1494  1618  NaN            NaN  2019   1
4 2019-01-03  7344  1467  1477  NaN            NaN  2019   1

In [13]:
df1= all_data.groupby(['車站名稱','年份','月份'])[['進站人數','出站人數']].agg([('平均','mean'),('總合','sum')])
df1

                進站人數               出站人數
                  平均    總合           平均    總合
車站名稱 年份   月份
七堵   2019 1   2337.0  2337  2892.000000  2892
          3   2362.0  2362  2509.000000  2509
          4   2405.0  2405  2496.000000  2496
          6   2466.0  2466  2672.000000  2672
          7   2333.0  2333  2057.000000  2057
...              ...   ...          ...   ...
百福   2024 4   3028.0  3028  2870.000000  2870
          7   3147.0  3147  3557.000000  3557
          8   3181.5  6363  2856.000000  5712
          9   2863.0  8589  2600.666667  7802
          10  3150.0  3150  3019.000000  3019

[325 rows x 4 columns]

In [17]:
df1.loc['七堵',2020]

      進站人數          出站人數
        平均    總合      平均    總合
月份
1   2601.0  2601  2711.0  2711
6   2555.0  2555  2441.0  2441
7   2598.0  2598  2618.0  2618
8   1858.0  1858  2020.0  2020
10  2595.0  2595  2903.0  2903
11  2219.5  4439  2384.5  4769
12  1961.0  1961  1918.0  1918