In [4]:
import pandas as pd

tips = pd.read_csv('tips.csv')
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  122 non-null    float64
 1   tip         122 non-null    float64
 2   smoker      122 non-null    object
 3   day         122 non-null    object
 4   time        122 non-null    object
 5   size        122 non-null    int64
dtypes: float64(2), int64(1), object(3)
memory usage: 5.8+ KB

In [5]:
#改變tips的欄位名稱
tips.columns = ['總票價', '小費', '是否吸菸', '日期', '時間', '人數']   
tips

       總票價    小費 是否吸菸    日期      時間  人數
0    21.85  3.86  Yes  Thur  Dinner   2
1    47.78  1.99  Yes   Mon   Lunch   1
2    37.94  3.05   No   Wed  Dinner   2
3    31.94  4.84  Yes   Mon  Dinner   3
4    12.02  8.36  Yes   Fri  Dinner   2
..     ...   ...  ...   ...     ...  ..
117  13.40  2.59  Yes   Mon  Dinner   3
118  45.17  9.46  Yes   Tue   Lunch   1
119  29.27  9.59   No   Sat  Dinner   5
120  41.33  9.23   No   Sun   Lunch   1
121  45.32  4.33   No   Mon  Dinner   2

[122 rows x 6 columns]

In [6]:
#欄位重新排列
tips = tips[['日期', '時間', '是否吸菸', '人數', '總票價', '小費']]

#新鄒一個欄位 小費佔總票價比例
tips['小費佔比'] = tips['小費'] / tips['總票價']
tips

/var/folders/dc/tk5t0pz15vx0wlrmz4r29s7w0000gn/T/ipykernel_51071/867659223.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tips['小費佔比'] = tips['小費'] / tips['總票價']

       日期      時間 是否吸菸  人數    總票價    小費      小費佔比
0    Thur  Dinner  Yes   2  21.85  3.86  0.176659
1     Mon   Lunch  Yes   1  47.78  1.99  0.041649
2     Wed  Dinner   No   2  37.94  3.05  0.080390
3     Mon  Dinner  Yes   3  31.94  4.84  0.151534
4     Fri  Dinner  Yes   2  12.02  8.36  0.695507
..    ...     ...  ...  ..    ...   ...       ...
117   Mon  Dinner  Yes   3  13.40  2.59  0.193284
118   Tue   Lunch  Yes   1  45.17  9.46  0.209431
119   Sat  Dinner   No   5  29.27  9.59  0.327639
120   Sun   Lunch   No   1  41.33  9.23  0.223324
121   Mon  Dinner   No   2  45.32  4.33  0.095543

[122 rows x 7 columns]

In [11]:
# 依照日期,建立一個群組
tips_grouped = tips.groupby('日期')
len(tips_grouped)

7

In [13]:
#計算小費平均值
tips_grouped['小費'].mean()
#計算小費平均值. 使用dataframe格式呈現
tips_grouped[['小費']].mean()

            小費
日期
Fri   5.244286
Mon   5.639565
Sat   6.162667
Sun   5.325000
Thur  4.726957
Tue   5.428462
Wed   5.410556

In [38]:
# 依據日期和是否抽煙建立群組
tips_grouped2 = tips.groupby(['日期', '是否吸菸'])

#取得小費的平均值
s1 = tips_grouped2['小費'].mean()

#s1是一個多層索引的Series
#變成DataFrame
df1 = s1.unstack()
df1
print(df1)

# s1我要unstack, 日期在欄位, 是否吸煙在索引
df2 = s1.unstack(level='日期')
print(df2)
print(df2.T)

是否吸菸        No       Yes
日期
Fri   5.256667  5.235000
Mon   5.713636  5.571667
Sat   6.513333  5.636667
Sun   5.532222  5.058571
Thur  5.530833  3.850000
Tue   5.298571  5.580000
Wed   5.212500  5.806667
日期         Fri       Mon       Sat       Sun      Thur       Tue       Wed
是否吸菸
No    5.256667  5.713636  6.513333  5.532222  5.530833  5.298571  5.212500
Yes   5.235000  5.571667  5.636667  5.058571  3.850000  5.580000  5.806667
是否吸菸        No       Yes
日期
Fri   5.256667  5.235000
Mon   5.713636  5.571667
Sat   6.513333  5.636667
Sun   5.532222  5.058571
Thur  5.530833  3.850000
Tue   5.298571  5.580000
Wed   5.212500  5.806667

In [44]:
# 依據日期和是否抽煙建立群組
grouped2 = tips.groupby(['日期', '是否吸菸'])
df3 = grouped2['小費'].agg(['mean','sum','count']).unstack(level='日期')
df3.columns.names = ['統計量','日期']

#統計量欄位和日期欄位交換位置, 讓日期在前面, 統計量在後面
df4 = df3.swaplevel(axis=1)
df4.sort_index(axis=1, level=0)  #依照欄位的第一層排序
df4

日期,Fri,Mon,Sat,Sun,Thur,Tue,Wed,Fri,Mon,Sat,...,Thur,Tue,Wed,Fri,Mon,Sat,Sun,Thur,Tue,Wed
統計量,mean,mean,mean,mean,mean,mean,mean,sum,sum,sum,...,sum,sum,sum,count,count,count,count,count,count,count
是否吸菸,,,,,,,,,,,,,,,,,,,,,
No,5.256667,5.713636,6.513333,5.532222,5.530833,5.298571,5.212500,31.54,62.85,58.62,...,66.37,37.09,62.55,6,11,9,9,12,7,12
Yes,5.235000,5.571667,5.636667,5.058571,3.850000,5.580000,5.806667,41.88,66.86,33.82,...,42.35,33.48,34.84,8,12,6,7,11,6,6