In [1]:
import pandas as pd

dataFrame = pd.read_csv('world.csv')
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 548751 entries, 0 to 548750
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID              548751 non-null  int64
 1   iso_code        524887 non-null  object
 2   洲名              507679 non-null  object
 3   國家              548751 non-null  object
 4   日期              548751 non-null  object
 5   總確診數            535599 non-null  float64
 6   新增確診數           532023 non-null  float64
 7   七天移動平均新增確診數     530814 non-null  float64
 8   總死亡數            535599 non-null  float64
 9   新增死亡數           532957 non-null  float64
 10  七天移動平均新增死亡數     531745 non-null  float64
 11  七天移動平均疫苗新增接種劑數  202840 non-null  float64
 12  每百人接種疫苗劑數       83222 non-null   float64
 13  每百人接種疫苗人數       79011 non-null   float64
 14  疫情控管指數          202760 non-null  float64
 15  總人口數            531268 non-null  float64
 16  中位數年紀           524815 non-null  float64
 17  70歲以上人口比例       0 non-null       float64
 18  平均壽命            526966 non-null  float64
 19  超額死亡率(%)        13737 non-null   float64
 20  超額死亡累計(每百萬)     13703 non-null   float64
dtypes: float64(16), int64(1), object(4)
memory usage: 87.9+ MB

In [8]:
allDataFrame = dataFrame.reindex(columns=['洲名','國家', '日期','總確診數', '總死亡數'])
allDataFrame.head(10)
mask = allDataFrame["洲名"] == "Asia"
allDataFrame[mask]

          洲名           國家          日期     總確診數    總死亡數
0       Asia  Afghanistan  2020-01-01      NaN     NaN
1       Asia  Afghanistan  2020-01-02      NaN     NaN
2       Asia  Afghanistan  2020-01-03      NaN     NaN
3       Asia  Afghanistan  2020-01-04      0.0     0.0
4       Asia  Afghanistan  2020-01-05      0.0     0.0
...      ...          ...         ...      ...     ...
544438  Asia        Yemen  2025-11-19  11945.0  2159.0
544439  Asia        Yemen  2025-11-20  11945.0  2159.0
544440  Asia        Yemen  2025-11-21  11945.0  2159.0
544441  Asia        Yemen  2025-11-22  11945.0  2159.0
544442  Asia        Yemen  2025-11-23  11945.0  2159.0

[105624 rows x 5 columns]

In [10]:
#選取台灣的資料
mask = allDataFrame["國家"] == "Taiwan"
taiwanData = allDataFrame[mask]
taiwanData

          洲名      國家          日期  總確診數  總死亡數
474651  Asia  Taiwan  2020-01-01   NaN   NaN
474652  Asia  Taiwan  2020-01-02   NaN   NaN
474653  Asia  Taiwan  2020-01-03   NaN   NaN
474654  Asia  Taiwan  2020-01-04   NaN   NaN
474655  Asia  Taiwan  2020-01-05   NaN   NaN
...      ...     ...         ...   ...   ...
476056  Asia  Taiwan  2025-08-31   NaN   NaN
476057  Asia  Taiwan  2025-09-30   NaN   NaN
476058  Asia  Taiwan  2025-10-31   NaN   NaN
476059  Asia  Taiwan  2025-11-30   NaN   NaN
476060  Asia  Taiwan  2025-12-31   NaN   NaN

[1410 rows x 5 columns]