In [ ]:
import yfinance as yf

ticker = "2330.TW"
start_date = "2025-01-01"
end_date = "2025-12-31"
data = yf.download(ticker, start=start_date, end=end_date, interval="1d",auto_adjust=True)
type(data)

[*********************100%***********************]  1 of 1 completed

pandas.core.frame.DataFrame

In [4]:
data.tail()

Price        Close    High     Low    Open    Volume
Ticker     2330.TW 2330.TW 2330.TW 2330.TW   2330.TW
Date
2025-12-22  1465.0  1470.0  1455.0  1465.0  22661665
2025-12-23  1490.0  1490.0  1470.0  1475.0  20739075
2025-12-24  1495.0  1500.0  1485.0  1495.0  12987261
2025-12-26  1510.0  1510.0  1495.0  1505.0  18823612
2025-12-29  1530.0  1530.0  1510.0  1515.0  23181700

In [6]:
start_date = "2025-01-01"
end_date = "2025-12-31"
stickers = ["2330.TW", "2303.TW", "2454.TW", "2317.TW"]
data = {ticker: yf.download(ticker, start=start_date, end=end_date, interval="1d",auto_adjust=True) for ticker in stickers}
data

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

{'2330.TW': Price             Close         High          Low         Open    Volume
 Ticker          2330.TW      2330.TW      2330.TW      2330.TW   2330.TW
 Date
 2025-01-02  1047.881714  1057.720979  1038.042449  1052.801346  43177098
 2025-01-03  1057.720947  1067.560212  1057.720947  1062.640580  30415096
 2025-01-06  1106.917236  1106.917236  1077.399443  1082.319076  69289786
 2025-01-07  1111.836792  1141.354583  1111.836792  1131.515319  48758688
 2025-01-08  1087.238770  1111.836932  1087.238770  1092.158402  45211419
 ...                 ...          ...          ...          ...       ...
 2025-12-22  1465.000000  1470.000000  1455.000000  1465.000000  22661665
 2025-12-23  1490.000000  1490.000000  1470.000000  1475.000000  20739075
 2025-12-24  1495.000000  1500.000000  1485.000000  1495.000000  12987261
 2025-12-26  1510.000000  1510.000000  1495.000000  1505.000000  18823612
 2025-12-29  1530.000000  1530.000000  1510.000000  1515.000000  23181700

 [240 rows x 5 columns],
 '2303.TW': Price           Close       High        Low       Open    Volume
 Ticker        2303.TW    2303.TW    2303.TW    2303.TW   2303.TW
 Date
 2025-01-02  41.049957  41.049957  40.251501  40.298471  65305876
 2025-01-03  40.486340  41.472669  40.486340  41.284796  42345224
 2025-01-06  40.768150  41.096924  40.721180  40.956019  30917178
 2025-01-07  39.781818  41.143888  39.781818  41.002987  58823388
 2025-01-08  40.110596  40.298468  39.781818  39.828789  37912494
 ...               ...        ...        ...        ...       ...
 2025-12-22  50.900002  51.099998  50.400002  51.000000  65719784
 2025-12-23  50.000000  51.000000  49.650002  51.000000  45790969
 2025-12-24  49.650002  50.000000  49.299999  49.900002  47697812
 2025-12-26  49.950001  50.099998  49.549999  49.849998  40760795
 2025-12-29  49.650002  49.950001  49.400002  49.950001  21555960

 [240 rows x 5 columns],
 '2454.TW': Price             Close         High          Low         Open    Volume
 Ticker          2454.TW      2454.TW      2454.TW      2454.TW   2454.TW
 Date
 2025-01-02  1323.937988  1372.972729  1309.227566  1368.069255   6820305
 2025-01-03  1338.648438  1343.551912  1309.227593  1338.648438   5752498
 2025-01-06  1397.490112  1397.490112  1363.165794  1363.165794   6907233
 2025-01-07  1461.235352  1471.042300  1387.683237  1417.104083  12307998
 2025-01-08  1441.621460  1471.042306  1431.814511  1471.042306  10805038
 ...                 ...          ...          ...          ...       ...
 2025-12-22  1400.000000  1435.000000  1390.000000  1430.000000   5675053
 2025-12-23  1390.000000  1405.000000  1380.000000  1405.000000   5114619
 2025-12-24  1380.000000  1400.000000  1380.000000  1395.000000   3022674
 2025-12-26  1385.000000  1395.000000  1380.000000  1390.000000   3000352
 2025-12-29  1420.000000  1425.000000  1380.000000  1390.000000   6636361

 [240 rows x 5 columns],
 '2317.TW': Price            Close        High         Low        Open    Volume
 Ticker         2317.TW     2317.TW     2317.TW     2317.TW   2317.TW
 Date
 2025-01-02  176.104248  179.481590  175.139293  177.551680  38301022
 2025-01-03  174.656815  177.551679  174.174337  176.586724  46698161
 2025-01-06  178.034164  180.929029  177.069210  178.516642  66600965
 2025-01-07  183.341415  185.271325  179.964074  180.446551  80605094
 2025-01-08  181.411499  183.341409  180.446544  183.341409  40650155
 ...                ...         ...         ...         ...       ...
 2025-12-22  224.000000  225.500000  223.000000  224.500000  39334152
 2025-12-23  224.000000  226.000000  223.500000  225.500000  29072621
 2025-12-24  224.000000  227.500000  224.000000  225.500000  35691897
 2025-12-26  225.500000  227.500000  224.500000  225.500000  28309367
 2025-12-29  231.000000  233.000000  226.500000  227.000000  57716483

 [240 rows x 5 columns]}

In [11]:
import pandas as pd

data1 = {key:dataframe['Close'][key] for key, dataframe in data.items()}
price_df = pd.DataFrame(data1) #講series轉dataframe, key是欄位名稱
price_df1 = price_df.rename(columns={'2330.TW':'台積電', '2303.TW':'聯電', '2454.TW':'聯發科', '2317.TW':'鴻海'})
price_df1

                    台積電         聯電          聯發科          鴻海
Date
2025-01-02  1047.881714  41.049957  1323.937988  176.104248
2025-01-03  1057.720947  40.486340  1338.648438  174.656815
2025-01-06  1106.917236  40.768150  1397.490112  178.034164
2025-01-07  1111.836792  39.781818  1461.235352  183.341415
2025-01-08  1087.238770  40.110596  1441.621460  181.411499
...                 ...        ...          ...         ...
2025-12-22  1465.000000  50.900002  1400.000000  224.000000
2025-12-23  1490.000000  50.000000  1390.000000  224.000000
2025-12-24  1495.000000  49.650002  1380.000000  224.000000
2025-12-26  1510.000000  49.950001  1385.000000  225.500000
2025-12-29  1530.000000  49.650002  1420.000000  231.000000

[240 rows x 4 columns]

In [12]:
price_df1.corr()

          台積電        聯電       聯發科        鴻海
台積電  1.000000  0.613020 -0.006275  0.953937
聯電   0.613020  1.000000 -0.303515  0.473373
聯發科 -0.006275 -0.303515  1.000000  0.056916
鴻海   0.953937  0.473373  0.056916  1.000000